#!/usr/bin/env node
/**
 * Neuralis Black — GEO Audit SaaS Platform
 * Script: send-reports.js
 *
 * Sends audit reports to clients via email.
 * Usage: node scripts/send-reports.js [clientId]
 */

require("dotenv").config({ path: ".env.local" });
const nodemailer = require("nodemailer");
const { getClients, getLatestAuditReport } = require("../src/lib/airtable");

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || "587", 10),
  secure: process.env.SMTP_SECURE === "true",
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Format a score into a human-readable grade label.
 * @param {number} score - Score from 0 to 100.
 * @returns {string}
 */
function gradeLabel(score) {
  if (score >= 90) return "Excellent (A)";
  if (score >= 75) return "Good (B)";
  if (score >= 60) return "Average (C)";
  if (score >= 40) return "Below Average (D)";
  return "Poor (F)";
}

/**
 * Build the HTML email body for an audit report.
 * @param {object} client
 * @param {object} report
 * @returns {string}
 */
function buildEmailHtml(client, report) {
  const { scores = {}, recommendations = [] } = report;
  const overallScore = scores.overall ?? 0;

  const recItems = recommendations
    .slice(0, 5)
    .map((rec) => `<li style="margin-bottom:8px;">${rec}</li>`)
    .join("");

  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><title>GEO Audit Report</title></head>
<body style="font-family:Inter,sans-serif;background:#0A0A0A;color:#F9FAFB;padding:32px;">
  <h1 style="color:#6C63FF;">Neuralis Black — GEO Audit Report</h1>
  <p>Hello <strong>${client.name}</strong>,</p>
  <p>Your latest Generative Engine Optimization audit is ready.</p>

  <table style="width:100%;border-collapse:collapse;margin:24px 0;">
    <tr>
      <td style="padding:12px;border:1px solid #374151;">Overall Score</td>
      <td style="padding:12px;border:1px solid #374151;font-weight:bold;">${overallScore}/100 — ${gradeLabel(overallScore)}</td>
    </tr>
    <tr>
      <td style="padding:12px;border:1px solid #374151;">Visibility</td>
      <td style="padding:12px;border:1px solid #374151;">${scores.visibility ?? "N/A"}/100</td>
    </tr>
    <tr>
      <td style="padding:12px;border:1px solid #374151;">Citation Rate</td>
      <td style="padding:12px;border:1px solid #374151;">${scores.citationRate ?? "N/A"}/100</td>
    </tr>
    <tr>
      <td style="padding:12px;border:1px solid #374151;">Content Relevance</td>
      <td style="padding:12px;border:1px solid #374151;">${scores.contentRelevance ?? "N/A"}/100</td>
    </tr>
  </table>

  ${
    recItems
      ? `<h2 style="color:#6C63FF;">Top Recommendations</h2><ul>${recItems}</ul>`
      : ""
  }

  <p style="color:#6B7280;font-size:12px;margin-top:32px;">
    Generated by Neuralis Black GEO Audit Platform • ${new Date().toLocaleDateString()}
  </p>
</body>
</html>
  `.trim();
}

async function sendReportToClient(client) {
  const report = await getLatestAuditReport(client.id);

  if (!report) {
    console.warn(`  ⚠️  No report found for ${client.name} (${client.id})`);
    return { success: false, clientId: client.id, reason: "No report found" };
  }

  const html = buildEmailHtml(client, report);

  await transporter.sendMail({
    from: `"Neuralis Black" <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
    to: client.email,
    subject: `Your GEO Audit Report — ${new Date().toLocaleDateString()}`,
    html,
  });

  console.log(`  ✅ Report sent to ${client.name} <${client.email}>`);
  return { success: true, clientId: client.id };
}

async function main() {
  const clientId = process.argv[2];

  try {
    if (clientId) {
      const clients = await getClients({ id: clientId });
      if (!clients || clients.length === 0) {
        console.error(`Client not found: ${clientId}`);
        process.exit(1);
      }
      console.log(`\n📧 Sending report to client: ${clientId}\n`);
      await sendReportToClient(clients[0]);
    } else {
      console.log("\n📧 Sending reports to all active clients…\n");
      const clients = await getClients({ status: "active" });

      if (!clients || clients.length === 0) {
        console.log("No active clients found.");
        process.exit(0);
      }

      const results = await Promise.allSettled(
        clients.map((c) => sendReportToClient(c))
      );

      const sent = results.filter(
        (r) => r.status === "fulfilled" && r.value.success
      ).length;
      console.log(`\n📊 Summary: ${sent}/${clients.length} reports sent.`);
    }
  } catch (err) {
    console.error("❌ Send-reports script failed:", err.message);
    process.exit(1);
  }
}

main();
